/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.kategoriDAO;
import DAO.menuDAO;
import java.awt.Frame;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import model.ModelMenu;
import service.serviceKategori;
import service.serviceMenu;
import tableModel.tableModelMenu;

/**
 *
 * @author MyBook Hype AMD
 */
public class formInputMenu extends JDialog {
    
    private final tableModelMenu tblModel = new tableModelMenu();
    private serviceMenu servis = new menuDAO();
    private ModelMenu menu;
    private int idMenu;
    private int row;
    
    private serviceKategori servis_ktg = new kategoriDAO();
    private int idKategori;
    private  Map<String, Integer> kategoriMap;
   
    public formInputMenu(Frame parent, boolean modal, int row, ModelMenu menu) {
        super(parent, modal);
        this.menu = menu;
        this.row = row;
        initComponents();
        kategoriMap = new HashMap<>();
        
        if(menu !=  null){
            dataTable();
        }
        loadData();
    }
    public formInputMenu() {
        super((Frame) null, true); // default null parent, modal true
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_simpan = new Palette.Custom_ButtonRounded();
        jLabel1 = new javax.swing.JLabel();
        txtNama = new Palette.JTextfieldRounded();
        jLabel3 = new javax.swing.JLabel();
        txtHarga = new Palette.JTextfieldRounded();
        jLabel8 = new javax.swing.JLabel();
        cbxKategori = new javax.swing.JComboBox<>();
        btn_Batal = new Palette.Custom_ButtonRounded();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(35, 12, 20));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ktegory.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Input Menu");

        btn_simpan.setBackground(new java.awt.Color(102, 153, 255));
        btn_simpan.setText("Simpan");
        btn_simpan.setFillOriginal(new java.awt.Color(105, 33, 58));
        btn_simpan.setFillOver(new java.awt.Color(105, 33, 58));
        btn_simpan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_simpan.setPreferredSize(new java.awt.Dimension(120, 19));
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama");

        txtNama.setForeground(new java.awt.Color(255, 255, 255));
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Harga");

        txtHarga.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Kategori");

        cbxKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilihi Kategori", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        cbxKategori.setPreferredSize(new java.awt.Dimension(21, 36));

        btn_Batal.setBackground(new java.awt.Color(102, 153, 255));
        btn_Batal.setText("Batal");
        btn_Batal.setFillOriginal(new java.awt.Color(105, 33, 58));
        btn_Batal.setFillOver(new java.awt.Color(105, 33, 58));
        btn_Batal.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_Batal.setPreferredSize(new java.awt.Dimension(120, 19));
        btn_Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxKategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Batal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Batal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
     if(btn_simpan.getText().equals("Simpan")){
         SimpanData();
     }else  if(btn_simpan.getText().equals("perbarui")){
         perbaruiData();
     }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btn_BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BatalActionPerformed
     dispose();
    }//GEN-LAST:event_btn_BatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(formInputMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            formInputMenu dialog = new formInputMenu(new javax.swing.JFrame(), true, 1, null);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        }
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Palette.Custom_ButtonRounded btn_Batal;
    private Palette.Custom_ButtonRounded btn_simpan;
    private javax.swing.JComboBox<String> cbxKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private Palette.JTextfieldRounded txtHarga;
    private Palette.JTextfieldRounded txtNama;
    // End of variables declaration//GEN-END:variables
    private boolean  validasiInput (){
    boolean valid = false;
    if (txtNama.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(null, "Nama Menu Tidak Boleh Kosong");
    }else if (txtHarga.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(null, "Harga Tidak Boleh Kosong");
    }else if (cbxKategori.getSelectedItem().equals("Pilih Kategori")){
        JOptionPane.showMessageDialog(null, "Harap Pilih Kategori");
    }else {
        valid = true;
    }  
    return valid; 
}
    
    private void SimpanData(){
        if(validasiInput()== true){
            String namaMenu       = txtNama.getText();
            Long Harga            = Long.parseLong(txtHarga.getText());
            String selected = cbxKategori.getSelectedItem().toString();
            int idKategori = Integer.parseInt(selected.split(" - ")[0]);

            
            ModelMenu menu = new ModelMenu();
            menu.setNamaMenu(namaMenu);
            menu.setHarga(Harga);
            menu.setIdKategori(idKategori);
            
            servis.tambahData(menu);
            tblModel.insertData(menu);
            resetForm();
        }
    }
    
     private void perbaruiData(){
        if(validasiInput()== true){
            String namaMenu       = txtNama.getText();
            Long Harga            = Long.parseLong(txtHarga.getText());
            String selected = cbxKategori.getSelectedItem().toString();
            int idKategori = Integer.parseInt(selected.split(" - ")[0]);

            
            ModelMenu menu = new ModelMenu();
            menu.setIdMenu(idMenu);
            menu.setNamaMenu(namaMenu);
            menu.setHarga(Harga);
            menu.setIdKategori(idKategori);
            
            servis.updateData(menu);
            tblModel.updateData(row, menu);
            resetForm();
            dispose();
        }
}

    private void resetForm() {
        txtNama.setText("");
        txtHarga.setText("");
        cbxKategori.setSelectedIndex(0);
    }

    private void dataTable() {
        btn_simpan.setText("Perbarui");
        idMenu = menu.getIdMenu();
        txtNama.setText(menu.getNamaMenu());
        txtHarga.setText(String.valueOf(menu.getHarga()));
        cbxKategori.setSelectedItem(menu.getIdKategori());
    }

    private void loadData() {
        List<ModelMenu> list = servis.tampilData();
        tblModel.setData(list);
    }
    
    private void ambilKategori(){
        
    }
    
   
    
}

