/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import config.koneksi;
import com.mysql.cj.protocol.Message;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.*;
import javax.swing.AbstractAction;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import main.MenuKasir;
import main.MenuUtama;

public class formlogin extends javax.swing.JFrame {

    int xx, xy;
    private Connection conn;

    public formlogin() {
        initComponents();
        conn = koneksi.getConnection();
        setActionButton();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t_username = new Palette.JTextfieldRounded();
        t_password = new Palette.Custom_JPasswordFieldRounded();
        btn_login = new Palette.Custom_ButtonRounded();
        eye = new javax.swing.JLabel();
        hideEye = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_username.setBorder(null);
        t_username.setText("Username");
        t_username.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(t_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, -1, -1));

        t_password.setBorder(null);
        t_password.setText("password\n");
        t_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(t_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, 180, 40));

        btn_login.setBackground(new java.awt.Color(255, 255, 255));
        btn_login.setForeground(new java.awt.Color(0, 0, 0));
        btn_login.setText("Login\n");
        btn_login.setFillOriginal(new java.awt.Color(255, 255, 255));
        btn_login.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, 140, 50));

        eye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Eyes.png"))); // NOI18N
        getContentPane().add(eye, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 490, -1, -1));

        hideEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Hide.png"))); // NOI18N
        getContentPane().add(hideEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 490, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Login (5).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void t_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formlogin().setVisible(true);
            }
        });
    }

    //fungsi eye 
    private void setActionButton() {
        eye.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                eye.setVisible(false);
                hideEye.setVisible(true);
                t_password.setEchoChar((char) 0); // Menampilkan password
            }
        });

        hideEye.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                eye.setVisible(true);
                hideEye.setVisible(false);
                t_password.setEchoChar('*'); // Menyembunyikan password
            }
        });
        btn_login.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                prosesLogin();
            }

        });

        t_password.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    prosesLogin();
                }
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Palette.Custom_ButtonRounded btn_login;
    private javax.swing.JLabel eye;
    private javax.swing.JLabel hideEye;
    private javax.swing.JLabel jLabel1;
    private Palette.Custom_JPasswordFieldRounded t_password;
    private Palette.JTextfieldRounded t_username;
    // End of variables declaration//GEN-END:variables

    //validasi input
    private boolean validasiInput() {
        boolean valid = false;
        if (t_username.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username Tidak Boleh Kosong");
        } else if (t_password.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password Tidak Boleh Kosong");
        } else {
            valid = true;
        }
        return valid;
    }

    //proses chek login
    private String checkLogin(String Username, String Password) {
        if (conn != null) {
            try {
                String sql = "SELECT * FROM user WHERE Username=? AND password=?";
                PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, Username);
                st.setString(2, Password);

                ResultSet rs = st.executeQuery();
                if (rs.next()) {
                    return rs.getString("role"); // Mengambil role (admin/user)
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        return null;
    }

    private void prosesLogin() {
        if (validasiInput()) {
            String Username = t_username.getText();
            String Password = new String(t_password.getPassword());
            String Role = checkLogin(Username, Password); // Ambil role

            if (Role != null) {
                if (Role.equals("Admin")) {
                    new MenuUtama().setVisible(true); // Tampilkan menu admin
                } else if (Role.equals("Karyawan")) {
                    new MenuKasir().setVisible(true); // Tampilkan menu user
                }
                dispose(); // Tutup halaman login
            } else {
                JOptionPane.showMessageDialog(this, "Username dan Password Salah", "pesan", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }

}
