/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

/**
 *
 * @author MyBook Hype AMD
 */
public class FormProfile extends javax.swing.JDialog {

    /**
     * Creates new form FormProfile
     */
    public FormProfile(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pn_btnPemesanan = new Palette.Panelcustom();
        jLabel10 = new javax.swing.JLabel();
        btn_pemesanan = new javax.swing.JLabel();
        pn_btnPemesanan1 = new Palette.Panelcustom();
        jLabel11 = new javax.swing.JLabel();
        btn_pemesanan1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pn_btnPemesanan.setRoundBottomRight(30);
        pn_btnPemesanan.setRoundBottomleft(30);
        pn_btnPemesanan.setRoundTopLeft(30);
        pn_btnPemesanan.setRoundTopRight(30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Purchase Order.png"))); // NOI18N
        jLabel10.setText("\n");
        jLabel10.setMaximumSize(new java.awt.Dimension(26, 30));
        jLabel10.setMinimumSize(new java.awt.Dimension(26, 30));
        jLabel10.setPreferredSize(new java.awt.Dimension(26, 30));

        btn_pemesanan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_pemesanan.setText("Ganti Password");
        btn_pemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pemesananMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pemesananMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pemesananMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnPemesananLayout = new javax.swing.GroupLayout(pn_btnPemesanan);
        pn_btnPemesanan.setLayout(pn_btnPemesananLayout);
        pn_btnPemesananLayout.setHorizontalGroup(
            pn_btnPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnPemesananLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_pemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 80, Short.MAX_VALUE))
        );
        pn_btnPemesananLayout.setVerticalGroup(
            pn_btnPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_btnPemesananLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(pn_btnPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pemesanan))
                .addContainerGap())
        );

        pn_btnPemesanan1.setRoundBottomRight(30);
        pn_btnPemesanan1.setRoundBottomleft(30);
        pn_btnPemesanan1.setRoundTopLeft(30);
        pn_btnPemesanan1.setRoundTopRight(30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Purchase Order.png"))); // NOI18N
        jLabel11.setText("\n");
        jLabel11.setMaximumSize(new java.awt.Dimension(26, 30));
        jLabel11.setMinimumSize(new java.awt.Dimension(26, 30));
        jLabel11.setPreferredSize(new java.awt.Dimension(26, 30));

        btn_pemesanan1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_pemesanan1.setText("Pemesanan");
        btn_pemesanan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pemesanan1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pemesanan1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pemesanan1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnPemesanan1Layout = new javax.swing.GroupLayout(pn_btnPemesanan1);
        pn_btnPemesanan1.setLayout(pn_btnPemesanan1Layout);
        pn_btnPemesanan1Layout.setHorizontalGroup(
            pn_btnPemesanan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnPemesanan1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_pemesanan1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_btnPemesanan1Layout.setVerticalGroup(
            pn_btnPemesanan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_btnPemesanan1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(pn_btnPemesanan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pemesanan1))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_btnPemesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_btnPemesanan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pn_btnPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnPemesanan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pemesananMouseClicked
//        pn_utama.removeAll();
//        pn_utama.repaint();
//        pn_utama.revalidate();
//        matiintombol();
//        pn_btnPemesanan.setBackground(new Color(105, 33, 58));
//        btn_pemesanan.setForeground(Color.white);
//        pn_utama.add(new menuPemesanan(userLogin));  // ✅ userLogin sekarang valid
//        pn_utama.repaint();
//        pn_utama.revalidate();
    }//GEN-LAST:event_btn_pemesananMouseClicked

    private void btn_pemesananMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pemesananMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pemesananMouseEntered

    private void btn_pemesananMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pemesananMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pemesananMouseExited

    private void btn_pemesanan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pemesanan1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pemesanan1MouseClicked

    private void btn_pemesanan1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pemesanan1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pemesanan1MouseEntered

    private void btn_pemesanan1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pemesanan1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pemesanan1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormProfile dialog = new FormProfile(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_pemesanan;
    private javax.swing.JLabel btn_pemesanan1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private Palette.Panelcustom pn_btnPemesanan;
    private Palette.Panelcustom pn_btnPemesanan1;
    // End of variables declaration//GEN-END:variables
}
